_wandb:
    value:
        cli_version: 0.23.0
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
Rollout Size:
    value: 2048
episodes:
    value: 1000
lr:
    value: 0.0003
