_wandb:
    value:
        cli_version: 0.23.0
        e:
            rcop2y2xikasglnmmar0wzfknas3wmk3:
                codePath: cleanTrain.py
                codePathLocal: cleanTrain.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "493408342016"
                        used: "456393134080"
                email: archer0030@gmail.com
                executable: /home/viole/Desktop/Cyr/En/.venv/bin/python3
                host: pop-os
                memory:
                    total: "7669522432"
                os: Linux-6.16.3-76061603-generic-x86_64-with-glibc2.35
                program: /home/viole/Desktop/Cyr/En/cleanTrain.py
                python: CPython 3.11.13
                root: /home/viole/Desktop/Cyr/En
                startedAt: "2025-11-18T22:01:14.237923Z"
                writerId: rcop2y2xikasglnmmar0wzfknas3wmk3
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
Rollout Size:
    value: 2048
episodes:
    value: 1000
lr:
    value: 0.0003
